repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.3
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
  # pyright
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.403
  hooks:
  - id: pyright