site_name: Config Finder
repo_url: https://github.com/fabfabi/configfinder

theme:
  name: readthedocs
  hljs_languages:
    - python
    - toml
    - json
    - yaml
plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        paths: [src]  # search packages in the src folder
        options:
          show_submodules: true
          docstring_style: google
    watch:
      - src/simpleconfigfinder

nav:
  - Start: 'index.md'
  - Code: 'configfinder.md'